language: node_js
node_js:
- v6
- v5
notifications:
  slack:
    rooms:
      secure: a1k/o/7iiiAK4OteR5O1X7ST3FnnweMfXXICxmEEe/yTRNvqQTNFaozE6JFxqLILp5Aq0pPe2bb9j4Hpr7/dylQn/4KhVuxW1IS7K0bQEeh0+O2Krj0UzBOrMErjbjHOo7AT5pbeqveArxLDYWEvDzGY/t2sydclRhLmSYxn53XxcQpS3uo+NC6jFzD1zzpQBVzsUXB/CzPCO1578q/2qp1gfP2G0oxW1rSJrSQPJydhEaFFF6yIQW2P9hCdfxrDMNo2v5tIEj+TWMbEqRwza7GVdFDouDtOtv3UlYLwsH2eecpJiSlcjFMNIncrJa84vOaOMW8/O3YziTVJMGMXMvt9tQjEavpj4+xcISbtkYy6If2unFsSbaU8EsQX3tEd90DyIc9X2fJA+LbRMDMxD0lQ8JjwzRrT8D0z8Tf/zeHNYEDY8kz1hOVaw2q9t08xBlx6YMhK14XxtzIznrpT98iEY6YmS8+M7cmhpVjQOdVF/fH3aWPKQL+tgmupYXwbD4V79zQYOdp4U7dnQ2PhGGNfZZhsnRjKaWomdf5nH9KHjYzfpU4/vLDXfWGDq7e/SFwda4UTnbz5I5aImDOruZGdHsPHh9EBat5CUqOp1dBUEiW6vGm8sWxS0rLUDBtvkNEW6ZNlnPd/3RXUBbhZhz3+x0fjDm3if1NuC2hMunw=
deploy:
  provider: heroku
  api_key:
    secure: SEvmNywcm37zdY0ODSaStCPvhyE23fX2zS/6eH2HIZXwAdZKcjGg018jfxYj8B0dkTbcDJcEsdnB1YIMmRfsB0U7mxH3D2SFcfJgNTjjzD31m6xMNqC9/C4kMbMpthO+CAs9KDcBhbvCKAOOItGoaohiy9cfc+5WMNxN5KJjuKvT1KnNjLl2+OlqARohleYKj6gzCd53fd2aRqfBs8wilLYAaSpvrTt5K7G7F+n7TB+8G22oX9pwhe6vCViQE6ulhy6gOLMtw+80Ncp3IULs2O+teQtE6bmrnvi6aN3G1DddY9CRL01wwDhiRXkZqNQYfuOd0+ox3aDfdA6hyqd/kYYh7niNytzHM0HSCkxVBClMXyE2/1p8C5vf0txMrJCHuRGlVMmuGlSGQMtNJmjEQh2jytQ92zPsvOaaJMLaO1yYjCqCbODX00AS0+N083YwvowkU0F0V+H5n2NoBSA+cBnnD82KGknL2kuLtTekgbhQen+uQZ4HiSPjSdLl6Fg532bENS82t6DFwCNFIjtPMf+Mb8Js2296+0Nsf36vp9PujBX/Wd1uBsUeDNxlyFGV+bPtZj/8LKw/1iKoNFM2JhzC1/52vIsRXZtG2eJhlF3CvBriKAoO/8qKTqYRPbq1BqTmV1ZM+1WOY+XZ7/azMgxx/Dq4mBGp5etmNmO/TBg=
  app: brocode
  on:
    repo: blugavere/brocode
